### ISSUE TITLE
getting filebot to run after download

### ISSUE THREAD

**Issue by dr01dy** [djerfy/docker-rutorrent#15]
Great project you have going here. I was looking for some help on how to get filebot to run after a file is downloaded. I didnt see anything in the .rtorrent.rc config. Just wondering if it should work out of the box or if you need to enable it.

Thanks

**Comment by djerfy** [comment]
Hi @dr01dy, 

A filebot configuration exists in the `.rtorrent.rc` file:
* Download finished: https://github.com/djerfy/docker-rutorrent/blob/latest/rootfs/home/torrent/.rtorrent.rc#L40
* Download erased: https://github.com/djerfy/docker-rutorrent/blob/latest/rootfs/home/torrent/.rtorrent.rc#L41

For the filebot configuration it's in `usr/local/bin/postdl` file: https://github.com/djerfy/docker-rutorrent/blob/latest/rootfs/usr/local/bin/postdl

**Comment by djerfy** [comment]
Hi @dr01dy,

If you have no other question I close this issue.
